baseURL = "https://icpc.ucsd.edu/"
languageCode = "en-us"
title = "Competitive Programming Club at UC San Diego"

[menu]
  [[menu.main]]
    identifier = "teams"
    name = "main-0"
    title = "Teams"
    url = "/teams/"
  [[menu.main]]
    identifier = "Contact"
    name = "main-1"
    title = "Contact Us"
    url = "/contact/"
  [[menu.main]]
    identifier = "Resources"
    name = "main-2"
    title = "Resources"
    url = "/resources/"